[dev]
  targetPort = 3000
  command = "npx vite dev"

[build]
  base = ""

[functions]
  directory = "functions/"
  node_bundler = "esbuild"

  external_node_modules = ["@libsql/client"]
  included_files = ["db/sqlite.db"]
