name: 'CI'

on:
  push:
    branches:
      - main

jobs:

  Build:
      runs-on: ubuntu-latest
      
      steps: 
        - name: Checkout code
          uses: actions/checkout@v2
        - run: npm ci
        - run: npm run build

  E2E_testing:
    needs: Build
    name: "E2E tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Serve and test.
        uses: cypress-io/github-action@v4
        with:
          start: netlify dev
          wait-on: 'http://localhost:8888'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MONGODB_PATH: ${{ secrets.MONGODB_PATH }}
    
  Deploy: 
    needs: E2E_testing
    name: "Deploy to Netlify"
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - run: npm ci
      - run: npm run build --if-present
      - name: Deploy
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'

  





