name: 'FE Build and test'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MONGODB_READ_PATH_DEV: ${{ secrets.MONGODB_READ_PATH_DEV }}
  MONGODB_READ_PATH: ${{ secrets.MONGODB_READ_PATH_DEV }}
on:
  push: 
    branches: 
      - main

jobs:

  Build:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./web
      steps: 
        - name: Checkout code
          uses: actions/checkout@v2
        - run: npm ci
        - run: npm run build

  E2E_testing:
    needs: Build
    name: "E2E tests"
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./web

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check env
        run: env
      - name: Serve and test.
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./web
          browser: chrome
          start: sudo netlify dev
          wait-on: 'http://localhost:8888'
          wait-on-timeout: 120

        
    
  # Deploy: 
  #   needs: E2E_testing
  #   name: "Deploy to Netlify"
  #   runs-on: ubuntu-latest
  #   defaults:
  #       run:
  #         working-directory: ./web

  #   steps:

  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - run: npm ci
  #     - run: npm run build --if-present
  #     - name: Deploy
  #       uses: netlify/actions/cli@master
  #       env:
  #         NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  #         NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  #       with:
  #         args: deploy --dir=build --prod
  #         secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'

  





